Misoten-B/airship-backend

README.md
=> add: README

docs/docs.go, docs/swagger.json, docs/swagger.yaml, internal/controller/business_card/business_card_controller.go
close #00
- business cardのupdateのparam形式修正
=> fix: business card update

.github/workflows/go.yml
close #19 
以下を参考にGithub Actions に判定を追加しました。
https://zenn.dev/camomile_cafe/articles/0e5f7a8cf4ade7
https://techblog.finatext.com/github-actions-how-to-disable-ci-in-draft-pull-requests-5989a228afaf
=> add: Github Actionsプルリクエストにアクティビティとドラフトの判定追加

.github/workflows/main_airship.yml
Reverts Misoten-B/airship-backend#22
=> Revert "Update main_airship.yml"

docs/docs.go, docs/swagger.json, docs/swagger.yaml, internal/controller/business_card/business_card_controller.go, internal/controller/business_card/dto/business_card_response.go
close #00
- swaggerにおけるbusinesscardにcoordinateの中身がなかったため、付け足した。
=> change: add coordinate

.env.sample, config/config.go, internal/middleware/Guard.go, main.go
close #00
- DEV_MODEが読み込めていないのを修正
- ~~PRD_MODEに変更~~
=> fix: 環境変数からDEV_MODE読み込み

docs/docs.go, docs/swagger.json, docs/swagger.yaml, internal/controller/business_card/business_card_controller.go, internal/controller/business_card_background/business_card_background_controller.go, internal/controller/business_card_background/dto/create_background_request.go, internal/controller/user/user_controller.go
=> fix: swagger

internal/database/model/ar_asset.go, internal/database/model/business_card.go, internal/database/model/user.go, scripts/migrate/main.go, scripts/seed/helper/factory.go, scripts/seed/main.go
close #34 
3Dモデルや名刺背景部分のサブタイプを中心に、Gormモデルの見直しを行ないます。
マイグレーションとデータ投入動作確認済み
=> change: Gormのモデル見直し

docs/docs.go, docs/swagger.json, docs/swagger.yaml, internal/controller/ar_assets/ar_assets_controller.go, internal/database/model/ar_asset.go, internal/database/model/status.go, internal/database/model/user.go, internal/domain/ar_assets/ar_assets.go, internal/domain/ar_assets/service/ar_assets_repository.go, internal/domain/ar_assets/service/qr_code_image_storage.go, internal/domain/shared/status.go, internal/domain/three_dimentional_model/service/three_dimentional_model_repository.go, internal/domain/three_dimentional_model/service/three_dimentional_model_service.go, internal/domain/three_dimentional_model/service/three_dimentional_model_storage.go, internal/domain/three_dimentional_model/three_dimentional_model.go, internal/domain/voice/service/voice_model_adapter.go, internal/domain/voice/service/voice_repository.go, internal/domain/voice/service/voice_service.go, internal/id/id.go, internal/infrastructure/ar_assets/azure_qr_code_image_storage.go, internal/infrastructure/ar_assets/gorm_ar_assets_repository.go, internal/infrastructure/three_dimentional_model/gorm_three_dimentonal_model.go, internal/infrastructure/voice/external_api_voice_model_adapter.go, internal/infrastructure/voice/gorm_voice_repository.go, internal/usecase/ar_assets.go, internal/usecase/ar_assets_factory.go, scripts/seed/helper/factory.go
#38 
ARアセット新規作成部分のユースケース実装。（本当はCRUDすべてやるつもりでしたが長くなりすぎたので分割、、、）
- オブジェクト生成周り（ ~現状、コントローラー層でベタ書きしてしまっています。~  後々パッケージなどを導入して改善したい、、、）
- テスト（ただし手動では動作確認済み）
- ~**リファクタリング**~ ある程度
現状、ユースケース層にすべての処理を記述していますが、必要ならサービスを追加で作成してそれを呼び出す形式に変更します。
=> Feat: ARアセット作成ユースケース

.github/ISSUE_TEMPLATE/feat.md
=> add: issue template

internal/drivers/azure_blob.go, internal/infrastructure/ar_assets/azure_qr_code_image_storage.go
=> feat: azure blob driver

.gitignore, Makefile, README.md, internal/domain/shared/path.go, internal/drivers/azure_blob.go
=> Feat azure blob container get

internal/frameworks/handler/business_card_background/handler.go
=> feat: 処理のみ

internal/application/usecase/ar_assets/create/usecase.go, internal/application/usecase/ar_assets/fetch_by_userid/usecase.go, internal/application/usecase/ar_assets/read_all/usecase.go, internal/container/wire.go, internal/container/wire_gen.go, internal/domain/ar_assets/ar_assets.go, internal/domain/ar_assets/service/ar_assets_repository.go, internal/domain/ar_assets/service/qr_code_image_storage.go, internal/domain/three_dimentional_model/service/three_dimentional_model_storage.go, internal/domain/voice/service/speaking_audio_storage.go, internal/drivers/azure_blob.go, internal/frameworks/handler/ar_assets/handler.go, internal/infrastructure/ar_assets/azure_qr_code_image_storage.go, internal/infrastructure/ar_assets/gorm_ar_assets_repository.go, internal/infrastructure/three_dimentional_model/azure_three_dimentional_model_storage.go, internal/infrastructure/voice/azure_speaking_audio_storage.go
#38 
ARアセット一覧取得の実装、動作確認済み。
containerパッケージが肥大化していますが、一旦見逃してください
=> Feat: ARアセット一覧取得

docs/docs.go, docs/swagger.json, docs/swagger.yaml, internal/application/usecase/ar_assets/status_done/usecase.go, internal/domain/ar_assets/service/ar_assets_repository.go, internal/drivers/database/mapper/status.go, internal/drivers/database/mapper/status_test.go, internal/frameworks/handler/ar_assets/handler.go, internal/frameworks/handler/user/handler.go, internal/frameworks/router/v1/internal/users/router.go, internal/infrastructure/ar_assets/gorm_ar_assets_repository.go
#60
AIと連携して行なうリソースの状態エンドポイントの実装を行ないます。
完了した際のエンドポイントのみを対象としています。
追記: 
また、音声モデルのエンドポイントは他のHTTPハンドラと同様にベタ書きで実装しています
=> Feat: 状態エンドポイント （完了のみ）

.github/workflows/deployment_airship-api.yml, .github/workflows/main_airship-api.yml, Dockerfile
=> feat: dockerfile for deployment

docs/docs.go, docs/swagger.json, docs/swagger.yaml, internal/application/usecase/three_dimentional_model/create/usecase.go, internal/application/usecase/three_dimentional_model/fetch_by_id/usecase.go, internal/application/usecase/three_dimentional_model/fetch_by_userid/usecase.go, internal/container/wire.go, internal/container/wire_gen.go, internal/domain/three_dimentional_model/read_model.go, internal/domain/three_dimentional_model/service/three_dimentional_model_repository.go, internal/domain/three_dimentional_model/service/three_dimentional_model_storage.go, internal/domain/three_dimentional_model/three_dimentional_model.go, internal/frameworks/handler/ar_assets/handler.go, internal/frameworks/handler/three_dimentional/handler.go, internal/infrastructure/three_dimentional_model/azure_three_dimentional_model_storage.go, internal/infrastructure/three_dimentional_model/gorm_three_dimentonal_model.go
#51 
3DモデルユースケースのCR（ID検索、一覧取得）を実装しました。動作確認済みです。
=> Feat: 3Dモデル CR

internal/frameworks/middleware/guard.go
=> fix: bearerないとエラーに

docs/docs.go, docs/swagger.json, docs/swagger.yaml, internal/frameworks/handler/user/handler.go
=> fix: getエンドポイント変更

README.md, internal/drivers/database/database.go, internal/frameworks/context.go, internal/frameworks/handler/ar_assets/handler.go, internal/frameworks/handler/business_card/handler.go, internal/frameworks/handler/business_card_background/handler.go, internal/frameworks/handler/business_card_parts_coordinate/handler.go, internal/frameworks/handler/three_dimentional/handler.go, internal/frameworks/handler/user/handler.go, main.go
close #77 
HTTPハンドラでGormオープンを行っていましたが、メイン実行ファイルに変更し、コネクションプールの設定も行ないました。
**起動時にデータベース接続が必須になりました**
=> Feat: Gormのコネクションプール設定

internal/frameworks/handler/three_dimentional/dto/three_dimentional_response.go
close #00
3Dmodelのレスポンスにjsonの形式が書いてなかったため、Upperで返ってきてたことの修正
=> fix: response

docs/docs.go, docs/swagger.json, docs/swagger.yaml, internal/frameworks/handler/business_card/dto/business_card_response.go
close #00
- responseのjson用の命名忘れ解消
=> fix: cards response

docs/docs.go, docs/swagger.json, docs/swagger.yaml, internal/frameworks/handler/ar_assets/dto/ar_assets_response.go, internal/frameworks/handler/ar_assets/dto/create_ar_assets_request.go, internal/frameworks/handler/business_card/dto/business_card_response.go, internal/frameworks/handler/business_card/dto/create_business_card_request.go, internal/frameworks/handler/business_card_background/dto/background_response.go, internal/frameworks/handler/business_card_background/dto/create_background_request.go, internal/frameworks/handler/business_card_parts_coordinate/dto/business_card_parts_coordinate_response.go, internal/frameworks/handler/user/dto/create_user_request.go, internal/frameworks/handler/user/dto/user_response.go
close #00
全てのjson部分のスネークケースをキャメルケースに
=> fix: snake to camel

internal/frameworks/handler/user/handler.go
close #00
update userをしたときに、音声をAzure Blobに保存するように
=> feat: putUserで音声を保存するように

docs/docs.go, docs/swagger.json, docs/swagger.yaml, internal/frameworks/handler/user/handler.go
close #00
user のupdateとdeleteのエンドポイントの修正
=> fix: endpoint

scripts/seed/helper/prd_factory.go, scripts/seed/main.go
=> feat: factory

docs/docs.go, docs/swagger.json, docs/swagger.yaml, go.mod, go.sum, internal/drivers/database/model/status.go, internal/frameworks/handler/user/dto/user_response.go, internal/frameworks/handler/user/handler.go
close #00
音声モデルのステータス情報のレスポンス漏れ修正
=> feat: usersハンドラに音声モデルの状態を表すレスポンス追加

internal/frameworks/router/v1/internal/users/router.go
close #90
ルーティングが正しく行われているか手動で確認しました。
HTTPハンドラが正しく処理を行なうかの確認
一部HTTPハンドラでバグが発見されました。そちらは #89 としてまとめてあります
=> fix: ルーティング確認

internal/frameworks/middleware/cors.go
=> fix: CORSのクライアント側に発生したバグ解消

docs/docs.go, docs/swagger.json, docs/swagger.yaml, internal/application/usecase/ar_assets/create/usecase.go, internal/frameworks/handler/ar_assets/dto/create_ar_assets_request.go, internal/frameworks/handler/ar_assets/handler.go, internal/frameworks/handler/user/handler.go
close #89 
issue参照
usersのUPDATEに関しては一旦、音声ファイルを必須にしてあります
必要なら修正お願いします @mitsuYashi
=> Fix HTTPハンドラの修正

docs/docs.go, docs/swagger.json, docs/swagger.yaml, internal/application/usecase/ar_assets/fetch_by_id/usecase.go, internal/application/usecase/ar_assets/fetch_by_id_public/usecase.go, internal/application/usecase/ar_assets/fetch_by_userid/usecase.go, internal/frameworks/handler/ar_assets/dto/ar_assets_response.go, internal/frameworks/handler/ar_assets/handler.go, internal/frameworks/handler/business_card/dto/business_card_response.go, internal/frameworks/handler/business_card/dto/create_business_card_request.go, internal/frameworks/handler/business_card_background/dto/background_response.go, internal/frameworks/handler/business_card_parts_coordinate/dto/business_card_parts_coordinate_response.go, internal/frameworks/handler/three_dimentional/dto/three_dimentional_response.go, internal/frameworks/handler/user/dto/create_user_request.go, internal/frameworks/handler/user/dto/user_response.go
=> feat: ARアセットの生成中リソースの取り扱い変更

internal/domain/ar_assets/ar_assets.go
=> fix: ARアセットのファイル名変更

scripts/migrate/main.go, scripts/seed/helper/factory.go, scripts/seed/helper/prd_factory.go
=> feat: dev factory

internal/frameworks/middleware/guard.go
=> hotfix: 本番用ログ確認

.air.toml, Dockerfile, compose.lint.yml, compose.yml
=> hotfix: アカウント登録時のfirebaseエラー修正

internal/domain/shared/status.go, internal/drivers/database/mapper/status.go, internal/drivers/database/model/status.go
=> hotfix: statusの値変更

docs/docs.go, docs/swagger.json, docs/swagger.yaml, internal/frameworks/handler/business_card_background/handler.go
=> fix: multipart/form-data

Makefile, internal/frameworks/handler/business_card_background/handler.go, scripts/seed/helper/factory.go, scripts/seed/helper/prd_factory.go
close #00
画像がない場合、URLを生成しないように
あとリファクタリング
=> Fix background not need

internal/frameworks/handler/user/handler.go
=> feat: ベタ書きで音声モデル生成リクエスト

internal/application/usecase/ar_assets/create/usecase.go, internal/domain/voice/service/voice_model_adapter.go, internal/frameworks/handler/user/handler.go, internal/infrastructure/ar_assets/gorm_ar_assets_repository.go, internal/infrastructure/voice/external_api_voice_model_adapter.go
=> Feat test user voice model

internal/application/usecase/ar_assets/create/usecase.go, internal/application/usecase/ar_assets/fetch_by_id/usecase.go, internal/application/usecase/ar_assets/fetch_by_id_public/usecase.go, internal/application/usecase/ar_assets/status_done/usecase.go, internal/application/usecase/three_dimentional_model/fetch_by_id/usecase.go, internal/domain/ar_assets/service/ar_assets_repository.go, internal/domain/three_dimentional_model/service/three_dimentional_model_repository.go, internal/frameworks/handler/business_card/handler.go, internal/frameworks/handler/business_card_background/handler.go, internal/frameworks/handler/user/handler.go, internal/infrastructure/ar_assets/gorm_ar_assets_repository.go, internal/infrastructure/three_dimentional_model/gorm_three_dimentonal_model.go, scripts/seed/helper/prd_factory.go
=> Feat: レコードが見つからない場合は404を返すように変更

internal/infrastructure/voice/external_api_voice_model_adapter.go
=> ステータスコードでも判定

docs/docs.go, docs/swagger.json, docs/swagger.yaml, internal/frameworks/handler/business_card_background/dto/create_background_request.go, internal/frameworks/handler/business_card_background/handler.go
=> feat: 名刺背景画像をオプショナルに

internal/infrastructure/voice/azure_speaking_audio_storage.go
=> hotfix: container name

docs/docs.go, docs/swagger.json, docs/swagger.yaml, internal/frameworks/handler/business_card/dto/business_card_response.go
=> hotfix: 名刺一覧レスポンス

internal/application/usecase/ar_assets/fetch_by_id/usecase.go, internal/application/usecase/ar_assets/fetch_by_userid/usecase.go, internal/frameworks/handler/business_card/handler.go
close #00
QRコードアイコン画像が存在しない場合はカラ文字列を返すように変更
=> Feat QRコードアイコン画像が登録されていない場合の挙動変更

internal/frameworks/handler/business_card/handler.go
=> fix: 公開用名刺取得のバグ修正

docs/docs.go, docs/swagger.json, docs/swagger.yaml, internal/application/usecase/ar_assets/delete_ar_assets/usecase.go, internal/application/usecase/ar_assets/delete_qr_code_icon/usecase.go, internal/application/usecase/ar_assets/update_ar_assets/usecase.go, internal/drivers/azure_blob.go, internal/frameworks/handler/ar_assets/dto/update_ar_assets_request.go, internal/frameworks/handler/ar_assets/handler.go, internal/frameworks/handler/business_card/handler.go, internal/frameworks/handler/business_card_background/handler.go, internal/frameworks/handler/three_dimentional/handler.go, internal/frameworks/router/v1/internal/users/router.go, internal/infrastructure/ar_assets/gorm_ar_assets_repository.go
=> Feat: ベタ書きUD

internal/frameworks/handler/business_card/handler.go
=> fix: container name

internal/frameworks/handler/business_card/handler.go
=> feat: エラーをフロントに返すように
